version: "3"

services:
  redis:
    image: redis:3.0-alpine
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    volumes:
      - "db:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@localhost
      - PGADMIN_DEFAULT_PASSWORD=password
  dj-snakeeyes:
    container_name: backend-skeleton
    build: backend
    command: sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db

  celery:
    build: backend
    command: celery -A backend worker -l info
    depends_on:
      - dj-snakeeyes
      - db


volumes:
  db:
  redis:

